spring:
  main:
    web-application-type: servlet
  application:
    name: CodeCompass
  datasource:
    url: jdbc:postgresql://localhost:5432/code_compass_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bvni
  jpa: #Config JPA Hibernate DDL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/code-compass-api
  threads:
    virtual:
      enabled: true

# Config Server Path and BaseUri for media
media:
  server-path: /home/panha/Pictures/media/
  base-uri: http://localhost:8081/media/

server:
  port: 8081
  forward-headers-strategy: none

judge0:
  protocol: http
  domain: judge0-code-compass.devith.it.com
#  port: 8888
  auth-token: ""

keycloak-admin:
  server-url: http://localhost:8080
  realm: code-compass-api
  client-id: admin-cli
  client-secret: Fw12zDEkORHYLrKgUpufo7cgrjepWLQa

logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG
    io.netty: DEBUG