spring:
  application:
    name: CodeCompass
  datasource: #Config Datasource (PostgreSql)
    url: jdbc:postgresql://localhost:9999/code_compass_db
    driver-class-name: org.postgresql.Driver
    username: benz
    password: benz
  jpa: #Config JPA Hibernate DDL
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate.hibernate.format_sql: true
  elasticsearch: #Config Elasticsearch
    uris: https://elastic.devith.it.com
    username: elastic
    password: benz3528
  security: #Config Resource Server Keycloak
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keyy.devith.it.com/realms/code-compass

# Config Server Path and BaseUri for media
media:
  server-path: /home/benz/ISTAD/SPRING/medias/
  base-uri: http://localhost:8080/media/