spring:
  main:
    web-application-type: servlet
  application:
    name: CodeCompass
  datasource:
    url: jdbc:postgresql://code-compass-db:5432/code_compass_db
    driver-class-name: org.postgresql.Driver
    username: benz
    password: benz
    hikari:
      initialization-fail-timeout: 30000
  jpa: #Config JPA Hibernate DDL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true

  elasticsearch: #Config Elasticsearch
    uris: https://elastic.devith.it.com
    username: elastic
    password: benz3528

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://keyy.devith.it.com/realms/code-compass
  threads:
    virtual:
      enabled: true

# Config Server Path and BaseUri for media
media:
  server-path: /app/media/
  base-uri: http://localhost:8081/media/

server:
  forward-headers-strategy: none
>>>>>>> f39d1aee214f5fce57ee04c38005ae16415310ef
  port: 8080
>>>>>>> 63d5524485d2eda0400136db9e5c5f4f1c893f3f

judge0:
  protocol: http
  domain: judge0-code-compass.devith.it.com
  #  port: 8888
  auth-token: ""
  http-connection-timeout: 10s
  http-read-timeout: 30s
  http-write-timeout: 15s
  submission-request-timeout: 30s
  polling-timeout: 10s
  total-polling-timeout: 3m
  initial-polling-delay: 1s
  max-polling-interval: 5s
  max-polling-attempts: 36
  cpu-time-limit: 2.0
  wall-time-limit: 10.0
  memory-limit: 256000

keycloak-admin:
  server-url: https://keyy.devith.it.com
  realm: code-compass
  client-id: nextjs
  client-secret: rHTSRHjbS7WwfOvfze1aO6hrgjsa7r2i

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs

logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG
    io.netty: DEBUG